name: cat_lovers
description: An app for the cats lovers
version: 1.0.0+1
environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.0
  dio: ^5.1.1
  flutter_riverpod: ^2.3.6
  go_router: ^7.0.0
  cached_network_image: ^3.2.3
  any_link_preview: ^3.0.0
  url_launcher: ^6.1.10
  octo_image: ^1.0.2
  share_plus: ^4.5.3
  shimmer: ^2.0.0

dev_dependencies:
  freezed: ^2.3.2
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  json_serializable: ^6.6.1

flutter:
  uses-material-design: true

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.jpeg"
  min_sdk_android: 21 # android min sdk min:16, default 21

  web:
    generate: true
  linux:
    generate: true
  windows:
    generate: true
  macos:
    generate: true